### ISSUE TITLE
Input Parameters (i.e. Variable) Do Not Support Multiple Values

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/create-release-action#239]
Various input parameters (i.e. `variable`) are scoped to supporting a single value when they should support multiple values either through multi-line input. This issue proposes the updating of the following parameters:

| Old Input Name | New Input Name | Comments |
| - | - | - |
| `deploy_to` | (unchanged) | use parallel execution using job matrix |
| `tenant` | `tenants` | `tenant`: deprecated<br>`tenants`: optional with support for multiple tenants |
| `tenant_tag` | `tenant_tags` | `tenant_tag`: deprecated<br>`tenant_tags`: optional with support for multiple tenant tags |
| `variable` | `variables` | `variable`: deprecated<br>`variables`: optional with support for multiple variables |

**Comment by derekbking** [comment]
Does this apply to the deploy_to input? The docs say to supply the argument multiple times. The meaning of this is not very clear to me. Specifying deploy_to twice under the with section results in an error complaining about multiple values. Comma delimited values do not seem to be working either.

Defining the step twice causes a conflict in duplicate releases. How can I deploy to multiple environments. Not sure if this issue related to mine.
`      - name: Create and deploy release (ENV1) 🐙
        if: ${{ inputs.pushToOctopus}}
        uses: OctopusDeploy/create-release-action@v1.1.2
        with:
          api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          server: ${{ secrets.OCTOPUSSERVERURL }}
          space: ${{ secrets.OCTOPUSSERVER_SPACE }}
          project: ${{ github.event.repository.name }}
          deploy_to: "ENV1"
          progress: true

      - name: Create and deploy release (ENV2) 🐙
        if: ${{ inputs.pushToOctopus}}
        uses: OctopusDeploy/create-release-action@v1.1.2
        with:
          api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          server: ${{ secrets.OCTOPUSSERVERURL }}
          space: ${{ secrets.OCTOPUSSERVER_SPACE }}
          project: ${{ github.event.repository.name }}
          deploy_to: "ENV2"
          progress: true`

Thank you.

**Comment by jbristowe** [comment]
Great feedback, @derekbking. Thanks. This was an oversight in the original design. I've updated the issue description (see above) to reflect our latest thoughts on this issue.

YAML supports multi-line inputs. Thus, if this change would occur, your snippet could be expressed more succinctly:

```yaml
- name: Create and deploy release 🐙
  if: ${{ inputs.pushToOctopus}}
  uses: OctopusDeploy/create-release-action@v1.1.2
  with:
    api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
    server: ${{ secrets.OCTOPUSSERVERURL }}
    space: ${{ secrets.OCTOPUSSERVER_SPACE }}
    project: ${{ github.event.repository.name }}
    deploy_to: |
      "ENV1"
      "ENV2"
    progress: true
```

Would this change match your expectations?
