### ISSUE TITLE
`wait_for_deployment` setting to true does not make the action wait

### ISSUE THREAD

**Issue by aziz-shahed-cko** [OctopusDeploy/create-release-action#271]
Hi,
Im using OctopusDeploy/create-release-action with the following set up
```
    - name: Create and deploy release
      uses: OctopusDeploy/create-release-action@v1.1.3
      with:
        api_key: ${{ inputs.OctopusApiKey }}
        server: ${{ inputs.OctopusServerUrl }}
        space: "Default"
        project: ${{ inputs.OctopusProjectName }}
        channel: ${{ inputs.OctopusChannelName }}
        release_number: ${{ inputs.Version }}
        progress: true
        wait_for_deployment: true
        deployment_timeout: ${{ inputs.OctopusDeploymentTimeout }}
```

I was expecting the action to wait and get feedback from octopus to indicate if the deployment was successful or not. But it does not wait and just says the release is created while on octopus server the release is in progress

🐙 Creating a release in Octopus Deploy...
🎉 Release 1.1.0 created successfully!

Expected behavior:
Action should wait for response from octopus server
