### ISSUE TITLE
V2 to V3 Upgrade Issue

### ISSUE THREAD

**Issue by zengshengliu** [OctopusDeploy/create-release-action#369]
I am trying to update from the v2 to v3 version of the `create-release-action`.
Here is my V2 config:
```yaml
      - name: Install Octopus CLI 🐙
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: 'latest'
      - name: Create Octopus Release
        uses: OctopusDeploy/create-release-action@v2
        env:
          OCTOPUS_HOST: ${{ secrets.OCTOPUS_CLI_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_APIKEY }}
          OCTOPUS_SPACE: 'Spaces-1'
        with:
          ignore_existing: true
          project: ${{ needs.names.outputs.repository_name }}
          packages: "*:${{ needs.get_version_tag.outputs.version }}"
          release_number: ${{ needs.get_version_tag.outputs.version }}
```
Here is my V3 config:
```yaml
      - name: Create Octopus Release
        uses: OctopusDeploy/create-release-action@v3
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_CLI_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_APIKEY }}
          OCTOPUS_SPACE: 'Default'
        with:
          ignore_existing: true
          project: ${{ needs.names.outputs.repository_name }}
          packages: "*:${{ needs.get_version_tag.outputs.version }}"
          release_number: ${{ needs.get_version_tag.outputs.version }}
```
(I have to switch from space id `Spaces-1` to space name `Default` for the `OCTOPUS_SPACE`, otherwise I will get the following error)
```
🐙 Creating a release in Octopus Deploy...
Error: Unable to resolve space name 'Spaces-1'
Error: Error: Unable to resolve space name 'Spaces-1'
```

The V2 one works without issue, but for V3, it is giving me the following error
```
🐙 Creating a release in Octopus Deploy...
Error: Error: The resource you requested was not found.
```

Is there something that I miss that could cause the issue?
