### ISSUE TITLE
Document OIDC Auth with Service Account ID instead of API Key

### ISSUE THREAD

**Issue by katrinajaneczko** [OctopusDeploy/create-release-action#556]
**Is your feature request related to a problem? Please describe.**
The README should include documentation of how to use the service account ID instead of an API key if the user desires. Right now, the documentation makes it sound like you MUST use an API key when that isn't the case, not accounting for the fact that auth with OIDC is possible.

**Describe the solution you'd like**
Add documentation/example of using service account ID instead of API key, and/or link out to docs.

**Describe alternatives you've considered**
Finding documentation elsewhere.

**Additional context**
Example workflow I've used:

```
    permissions:
      id-token: write
      contents: write

    env:
      OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
      OCTOPUS_SPACE: ExampleSpace
      OCTOPUS_SERVICE_ACCOUNT_ID: ${{ secrets.OCTOPUS_SERVICE_ACCOUNT_ID }}
      
    steps:

    - name: Login to Octopus
      uses: OctopusDeploy/login@v1
      with:
        server: ${{ env.OCTOPUS_URL }}
        service_account_id: ${{ env.OCTOPUS_SERVICE_ACCOUNT_ID }}

    - name: Create release in Octopus
      uses: OctopusDeploy/create-release-action@v3
      with:
        space: Spaces-1
        project: MyProject
        environments: development
```
